package com.kamomileware.define.term;

import com.kamomileware.define.model.term.Term;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static com.kamomileware.define.model.term.TermCategory.*;

/**
 * Created by pepe on 17/07/14.
 */
public class StaticTermRepository {

    private static List<Term> terms = Arrays.asList(new Term[]{
            new Term("Ambrosio", "El inmortal", NP),
            new Term("Templo", "Bar de moda", CH),
            new Term("O.M.N.I", "Objeto Marino No Identificado", SG),
            new Term("Ratería", "Bajeza en el trato", AB),
            new Term("Flavio", "Amarillo, dorado, rubio", NP),
            new Term("Entoligar", "Golpear", CH),
            new Term("F.U.E.", "Federacion Universitaria Escolar", SG),
            new Term("Humildad", "Sentimiento de propia inferioridad", AB),
            new Term("Eduvigis", "Lucha, pelea", NP),
            new Term("Chingón", "Colérico, propenso a enfadarse", CH),
            new Term("F.E.T.E.", "Federación Española de Trabajadores de la Enseñanza", SG),
            new Term("Exultar", "Regocijarse, dar saltos de alegría", AB),
            new Term("Job", "Afligido", NP),
            new Term("Gambear", "Pasear", CH),
            new Term("I.R.Y.D.A.", "Instituto Nacional de Reforma y Desarrollo Agrario", SG),
            new Term("Mansedumbre", "Apacibilidad", AB),
            new Term("Fidel", "Tener confianza", NP),
            new Term("Espeta", "Policía del Cuerpo Superior de Policía", CH),
            new Term("F.T.R.E", "Federación de Trabajadores de la Región Española", SG),
            new Term("Humanidad", "Compasión", AB),
            new Term("Reveriano", "Temer a alguien", NP),
            new Term("Macanear", "Hacer o decir tonterías", CH),
            new Term("O.U.A", "Organización de la Unión Africana", SG),
            new Term("Ricamente", "Con opulencia", AB),
            new Term("Jasón", "El que sanará", NP),
            new Term("Flauta", "Jeringuilla", CH),
            new Term("I.N.T.A", "Instituto Nacional de Técnicas Aeroespaciales", SG),
            new Term("Malograr", "Frustrarse", AB),
            new Term("Salomé", "Completo, perfecto", NP),
            new Term("Níquel", "De níquel: muy bien", CH),
            new Term("A.U.", "Alianza Universitaria", SG),
            new Term("Soltura", "Agilidad, desenvoltura", AB),
            new Term("Pamela", "Todo dulzura", NP),
            new Term("Liche", "Calle", CH),
            new Term("A.I.P.", "Acuerdo Intereuropeo de Pagos", SG),
            new Term("Rapiña", "Avidez", AB),
            new Term("Hiram", "El hermano es excelso", NP),
            new Term("Frusa", "Miedo", CH),
            new Term("I.E.F.", "Instituto de Estudios Fiscales", SG),
            new Term("Justipreciar", "Apreciar una cosa", AB),
            new Term("Rut", "Belleza", NP),
            new Term("Nave", "Coche, automóvil", CH),
            new Term("C.I.O.S.L.", "Confederación Internacional de Organizaciones Sindicales Libres", SG),
            new Term("Sobrecoger", "Asustar, intimidar", AB),
            new Term("Muriel", "Resplandeciente", NP),
            new Term("In", "Ser in: estar de moda", CH),
            new Term("R.E.N.F.E.", "Red Nacional de los Ferrocarriles Españoles", SG),
            new Term("Perplejidad", "Estado mental de confusión", AB),
            new Term("Ilidio", "Tropa", NP),
            new Term("Fa", "Dar la fa: avisar de un peligro a quienes cometen un delito", CH),
            new Term("I.E.P.", "Instituto de Estudios Politicos", SG),
            new Term("Lapsus", "Olvido", AB),
            new Term("Tamara", "Palmera de dátiles", NP),
            new Term("Pulguero", "Cama", CH),
            new Term("B.I.R.D", "Banco Internacional para la Reconstrucción y el Desarrollo", SG),
            new Term("Veleidad", "Deseo caprichoso", AB),
            new Term("Palmira", "Rama de la palmera", NP),
            new Term("Julepe", "Juego de cartas", CH),
            new Term("A.I.A.P", "Asociación Internacional de Artes Plásticas", SG),
            new Term("Radiestesia", "Sensibilidad para captar ciertas radiaciones", AB),
            new Term("Sebastián", "Digno de respeto", NP),
            new Term("Orinal", "Casco", CH),
            new Term("B.O.E.", "Boletín Oficial del Estado", SG),
            new Term("Sutileza", "Calidad de sutil", AB),
            new Term("Edgar", "Propiedad, riqueza", NP),
            new Term("Chasis", "El esqueleto", CH),
            new Term("F.E.D.A.S.", "Federación Española de Actividades Subacuáticas", SG),
            new Term("Espeluznar", "Aterrorizar", AB),
            new Term("Diana", "Claridad, cielo", NP),
            new Term("Chupano", "Celda de castigo", CH),
            new Term("E.S.T.E.", "Escuela Superior de Técnica Empresarial", SG),
            new Term("Encarar", "Enfrentarse a alguien o algo ", AB),
            new Term("Nadia", "Esperanza", NP),
            new Term("Iguales", "Pareja de la guardia civil", CH),
            new Term("R.N.E", "Radio Nacional Española", SG),
            new Term("Persistir", "Perseverar", AB),
            new Term("Alfonso", "Listo, preparado", NP),
            new Term("Arajai", "Sacerdote", CH),
            new Term("A.E.P.D", "Asociación Española de Periodistas Deportivos", SG),
            new Term("Angustia", "Malestar psíquico que hace sentir un temblor difuso", AB),
            new Term("Adolfo", "Guerrero de noble estirpe", NP),
            new Term("Agnusdei", "Estar echo un agnusdei: estar muy magullado o herido", CH),
            new Term("A.D.L.A.N.", "Amigos del Arte Nuevo", SG),
            new Term("Acholar", "Avergonzar", AB),
            new Term("Abigail", "Alegría del padre", NP),
            new Term("Abuchear", "Dejar, abandonar, tirar", CH),
            new Term("A.C.T.R.", "Antiguos Combatientes de Tercios de Requetés", SG),
            new Term("Aberración", "Apartamiento de lo que es normal, justo, correcto, lógico", AB),
            new Term("Wally", "Extranjero", NP),
            new Term("Surai", "Ojo", CH),
            new Term("F.I.A.", "Federación Internacional de Astronáutica", SG),
            new Term("Estoicismo", "Resistencia a las adversidades", AB),
            new Term("Uziel", "Dios es fuerte", NP),
            new Term("Sacristía", "La bragueta", CH),
            new Term("E.N.E.A.", "Agencia Europea para la Energia Nuclear", SG),
            new Term("Celotipia", "Pasión por los celos", AB),
            new Term("Tirza", "Ciprés", NP),
            new Term("Raspa", "Persona protestona", CH),
            new Term("C.I.S.A", "Comisión Internacional para el Salvamento Alpino", SG),
            new Term("Abandonar", "Entregar la voluntad a alguien", AB),
            new Term("Sindufo", "El lobo del camino", NP),
            new Term("Piltreo", "Sueño, acción de dormir", CH),
            new Term("O.M.S.", "Organización Mundial de la Salud", SG),
            new Term("Urbanidad", "Educación, cortesía", AB),
            new Term("Alvaro", "Prudente", NP),
            new Term("Arrear", "Ponerse en marcha, ir deprisa", CH),
            new Term("A.J.A.", "Agrupación Juvenil Amanecer", SG),
            new Term("Arrepentirse", "Sentir pesar por una acción u omisión", AB),
            new Term("Nereo", "Nadar", NP),
            new Term("Invento", "Ocurrencia", CH),
            new Term("S.E.N.P.A.", "Servicio Nacional de Productos Agrarios", SG),
            new Term("Picardía", "Intención deshonesta", AB),
            new Term("Emilio", "Amable, gracioso, cortés", NP),
            new Term("Domingo", "De domingo: elegante", CH),
            new Term("F.I.C.P.", "Federación Internacional de Clubes de Publicidad", SG),
            new Term("Fingir", "Dar a entender lo que no es verdad", AB),
            new Term("Jonás", "Paloma", NP),
            new Term("Garata", "Escándalo, alboroto", CH),
            new Term("I.U.C.E", "Instituto Universitario de Ciencias de la Empresa", SG),
            new Term("Maravilla", "Admiración", AB),
            new Term("Javier", "Casa nueva", NP),
            new Term("Gamba", "Billete de 5 euros", CH),
            new Term("I.N.V.", "Instituto Nacional de la Vivienda", SG),
            new Term("Malquistar", "Enemistar a 2 personas entre sí", AB),
            new Term("Israel", "El que dominó a Dios", NP),
            new Term("Fusca", "Escopeta de cañones recortados", CH),
            new Term("I.N.L.E.", "Instituto Nacional del Libro Español", SG),
            new Term("Madurar", "Desarrollarse espiritualmente", AB),
            new Term("Regina", "Reina", NP),
            new Term("Monago", "Estómago", CH),
            new Term("C.E.D.A.", "Confederación Española de Derechos Autónomos", SG),
            new Term("Resabiar", "Deleitarse en algo", AB),
            new Term("Pimpinela", "Sandía", NP),
            new Term("Lisa", "Tener la lisa: tener suerte", CH),
            new Term("C.I.V.", "Comisión Internacional del Vino", SG),
            new Term("Recato", "Modestia, honestidad", AB),
            new Term("Patricia", "Del padre libre o noble", NP),
            new Term("Lebrel", "Niño pequeño", CH),
            new Term("A.N.Q.U.E.", "Asociación Nacional de Químicos de España", SG),
            new Term("Rebato", "Alarma ante un acontecimiento insólito", AB),
            new Term("Mónica", "Solitaria", NP),
            new Term("Izarse", "Balancearse", CH),
            new Term("R.E.D.I.A.", "Red de Itinerarios Asfálticos", SG),
            new Term("Pereza", "Resistencia al trabajo", AB),
            new Term("Tabare", "El que vive sólo", NP),
            new Term("Plajo", "Cigarrillo", CH),
            new Term("O.I.T.", "Organización Internacional del Trabajo", SG),
            new Term("Vanidad", "Orgullo", AB),
            new Term("Milagros", "Maravilla", NP),
            new Term("Isidro", "Paleto", CH),
            new Term("P.O.U.", "Policia del Orden Universitario", SG),
            new Term("Peligro", "Riesgo de que ocurra algún mal", AB),
            new Term("Natalia", "Día natalicio", NP),
            new Term("Inflagatas", "Bobo, tonto", CH),
            new Term("S.E.E.A.", "Sociedad Europea de Energía Atómica", SG),
            new Term("Pesadumbre", "Motivo de aflicción", AB)

    });

    public static Term shuffleAndGet() {
        Collections.shuffle(terms);
        return terms.get(0);
    }

    public static Term get(int i) {
        return terms.get(i);
    }

    public static List<Term> get() {
        return terms;
    }
}
